### ISSUE TITLE
Error while training model in Google Colab

### ISSUE THREAD

**Issue by kr-sundaram** [kh-kim/simple-nmt#12]
Thanks for making your repo public.

I am using your repo for training model for EN to DE translation.

I tried to train translation model in google colab with runtime type as TPU, GPU and CPU but i am getting the below errors for all type as some memory issues, could you please let me know what could be done:

**Runtime type: TPU**
NLLLoss()
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "train.py", line 491, in <module>
    main(config)
  File "train.py", line 420, in main
    model.cuda(config.gpu_id)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 307, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 307, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47 

**Runtime type: GPU**
NLLLoss()
SGD (
Parameter Group 0
    dampening: 0
    initial_lr: 1.0
    lr: 1.0
    momentum: 0
    nesterov: False
    weight_decay: 0
)
/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
Current run is terminating due to exception: CUDA out of memory. Tried to allocate 2.58 GiB (GPU 0; 11.17 GiB total capacity; 8.93 GiB already allocated; 1.92 GiB free; 8.95 GiB reserved in total by PyTorch) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:289)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7ff00ff05536 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1cf1e (0x7ff01014ef1e in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1df9e (0x7ff01014ff9e in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #3: THCStorage_resize + 0x96 (0x7ff0113dce76 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: THCTensor_resizeNd + 0x441 (0x7ff0113ee031 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: THNN_CudaClassNLLCriterion_updateGradInput + 0x6a (0x7ff011c8ed4a in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x1027578 (0x7ff011388578 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xfab71b (0x7ff01130c71b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x10c33d3 (0x7ff048eda3d3 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x2b493d8 (0x7ff04a9603d8 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x10c33d3 (0x7ff048eda3d3 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::autograd::generated::NllLossBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x276 (0x7ff04a6bbda6 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2d89705 (0x7ff04aba0705 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7ff04ab9da03 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7ff04ab9e7e2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::thread_init(int) + 0x39 (0x7ff04ab96e59 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7ff0574de488 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0xbd6df (0x7ff059a9b6df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #18: <unknown function> + 0x76db (0x7ff05ab7d6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #19: clone + 0x3f (0x7ff05aeb6a3f in /lib/x86_64-linux-gnu/libc.so.6)
.
Engine run is terminating due to exception: CUDA out of memory. Tried to allocate 2.58 GiB (GPU 0; 11.17 GiB total capacity; 8.93 GiB already allocated; 1.92 GiB free; 8.95 GiB reserved in total by PyTorch) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:289)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7ff00ff05536 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1cf1e (0x7ff01014ef1e in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1df9e (0x7ff01014ff9e in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #3: THCStorage_resize + 0x96 (0x7ff0113dce76 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: THCTensor_resizeNd + 0x441 (0x7ff0113ee031 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: THNN_CudaClassNLLCriterion_updateGradInput + 0x6a (0x7ff011c8ed4a in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x1027578 (0x7ff011388578 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xfab71b (0x7ff01130c71b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x10c33d3 (0x7ff048eda3d3 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x2b493d8 (0x7ff04a9603d8 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x10c33d3 (0x7ff048eda3d3 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::autograd::generated::NllLossBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x276 (0x7ff04a6bbda6 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2d89705 (0x7ff04aba0705 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7ff04ab9da03 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7ff04ab9e7e2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::thread_init(int) + 0x39 (0x7ff04ab96e59 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7ff0574de488 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0xbd6df (0x7ff059a9b6df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #18: <unknown function> + 0x76db (0x7ff05ab7d6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #19: clone + 0x3f (0x7ff05aeb6a3f in /lib/x86_64-linux-gnu/libc.so.6)
.
Traceback (most recent call last):
  File "train.py", line 491, in <module>
    main(config)
  File "train.py", line 468, in main
    lr_scheduler=lr_scheduler,
  File "/content/drive/My Drive/Simple_NMT/simple_nmt/trainer.py", line 282, in train
    train_engine.run(train_loader, max_epochs=n_epochs)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 658, in run
    return self._internal_run()
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 722, in _internal_run
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 437, in _handle_exception
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 697, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 788, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 437, in _handle_exception
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 771, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/content/drive/My Drive/Simple_NMT/simple_nmt/trainer.py", line 61, in train
    loss.div(y.size(0)).backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 2.58 GiB (GPU 0; 11.17 GiB total capacity; 8.93 GiB already allocated; 1.92 GiB free; 8.95 GiB reserved in total by PyTorch) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:289)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7ff00ff05536 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1cf1e (0x7ff01014ef1e in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1df9e (0x7ff01014ff9e in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #3: THCStorage_resize + 0x96 (0x7ff0113dce76 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: THCTensor_resizeNd + 0x441 (0x7ff0113ee031 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: THNN_CudaClassNLLCriterion_updateGradInput + 0x6a (0x7ff011c8ed4a in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x1027578 (0x7ff011388578 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xfab71b (0x7ff01130c71b in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x10c33d3 (0x7ff048eda3d3 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x2b493d8 (0x7ff04a9603d8 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x10c33d3 (0x7ff048eda3d3 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::autograd::generated::NllLossBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x276 (0x7ff04a6bbda6 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2d89705 (0x7ff04aba0705 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7ff04ab9da03 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7ff04ab9e7e2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::thread_init(int) + 0x39 (0x7ff04ab96e59 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7ff0574de488 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0xbd6df (0x7ff059a9b6df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #18: <unknown function> + 0x76db (0x7ff05ab7d6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #19: clone + 0x3f (0x7ff05aeb6a3f in /lib/x86_64-linux-gnu/libc.so.6)

**Runtime type: CPU**
Traceback (most recent call last):
  File "./train.py", line 491, in <module>
    main(config)
  File "./train.py", line 468, in main
    lr_scheduler=lr_scheduler,
  File "C:\01_Development\Master_Thesis\Simple_NMT\simple_nmt\trainer.py", line 282, in train
    train_engine.run(train_loader, max_epochs=n_epochs)
  File "C:\Program Files (x86)\Python37\lib\site-packages\ignite\engine\engine.py", line 359, in run
    self._handle_exception(e)
  File "C:\Program Files (x86)\Python37\lib\site-packages\ignite\engine\engine.py", line 324, in _handle_exception
    raise e
  File "C:\Program Files (x86)\Python37\lib\site-packages\ignite\engine\engine.py", line 346, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "C:\Program Files (x86)\Python37\lib\site-packages\ignite\engine\engine.py", line 313, in _run_once_on_dataset
    self._handle_exception(e)
  File "C:\Program Files (x86)\Python37\lib\site-packages\ignite\engine\engine.py", line 324, in _handle_exception
    raise e
  File "C:\Program Files (x86)\Python37\lib\site-packages\ignite\engine\engine.py", line 305, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "C:\01_Development\Master_Thesis\Simple_NMT\simple_nmt\trainer.py", line 61, in train
    loss.div(y.size(0)).backward()
  File "C:\Program Files (x86)\Python37\lib\site-packages\torch\tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Program Files (x86)\Python37\lib\site-packages\torch\autograd\__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 6930739200 bytes. Buy new RAM!
(no backtrace available)

Could please help me how to get rid of this memory issues?

**Comment by kh-kim** [comment]
Hi @kr-sundaram , can you share the arguments that you tried?
